version: "3"

services:
  review:
    build: ./services/review
    volumes:
      - ./workdir:/workdir
  lint:
    build:
      context: .
      dockerfile: ./services/textlint
    volumes:
      - ./:/work
